@startuml

node "<<device>>\nLinux-PC" as os {
    node "Wildfly Container\n><size:10>0.0.0.0:8080->8080/tcp, 0.0.0.0:9990->9990/tcp</size>" {
        node Wildfly as AS {
            artifact simplechat.war as war
        }

    }

    node "Database Container\n<size:10>0.0.0.0:27017->27017</size>" {
        database mongodb as DB
    }
}

war - DB
@enduml